/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __HYDRO_H_
#define __HYDRO_H_

#include <fstream>
#include <iomanip>
#include <type_traits>
#include <limits>
#include <utility>
#include <cmath>
#include <rapidjson/document.h>
#include <Kokkos_Core.hpp>
#include <Kokkos_hwloc.hpp>
#include "nablalib/utils/Utils.h"
#include "nablalib/utils/Timer.h"
#include "nablalib/types/Types.h"
#include "nablalib/utils/kokkos/Parallel.h"
#include "CartesianMesh2D.h"

using namespace nablalib::utils;
using namespace nablalib::types;
using namespace nablalib::utils::kokkos;

class R1;
class R2;

/******************** Module declaration ********************/

class Hydro
{
	friend class R1;
	friend class R2;
public:
	Hydro(CartesianMesh2D& aMesh);
	~Hydro();

	void jsonInit(const char* jsonContent);

	void simulate();
	KOKKOS_INLINE_FUNCTION
	void hj1() noexcept;
	KOKKOS_INLINE_FUNCTION
	void hj2() noexcept;
	KOKKOS_INLINE_FUNCTION
	void hj3() noexcept;

private:
	// Mesh and mesh variables
	CartesianMesh2D& mesh;
	size_t nbNodes, nbCells;

	// Additional modules
	R1* r1;
	R2* r2;

	// Options and global variables
	double maxTime;
	int maxIter;
	double deltat;
	static constexpr double t = 0.0;
	Kokkos::View<RealArray1D<2>*> X;
	Kokkos::View<double*> hv1;
	Kokkos::View<double*> hv2;
	Kokkos::View<double*> hv3;
	Kokkos::View<double*> hv4;
	Kokkos::View<double*> hv5;
	Kokkos::View<double*> hv6;
	Kokkos::View<double*> hv7;

	// Timers
	Timer globalTimer;
	Timer cpuTimer;
	Timer ioTimer;
};

#endif
