/* DO NOT EDIT THIS FILE - it is machine generated */

package batilibjava;

public interface IBatiLib
{
	public void jsonInit(String jsonContent);
	public double nextWaveHeight();
	public double nextDepth1(double x0, double[] x1);
	public double nextDepth2(double x0, double[][] x1);
	public double[] nextDepth3(double[] x0);
	public double[][] nextDepth4(double[][] x0);
}
