/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __VARIABLES_H_
#define __VARIABLES_H_

#include <fstream>
#include <iomanip>
#include <type_traits>
#include <limits>
#include <utility>
#include <cmath>
#include <rapidjson/document.h>
#include <Kokkos_Core.hpp>
#include <Kokkos_hwloc.hpp>
#include "nablalib/utils/Utils.h"
#include "nablalib/utils/Timer.h"
#include "nablalib/types/Types.h"
#include "nablalib/utils/kokkos/Parallel.h"
#include "CartesianMesh2D.h"

using namespace nablalib::utils;
using namespace nablalib::types;
using namespace nablalib::utils::kokkos;

/******************** Module declaration ********************/

class Variables
{
	typedef Kokkos::TeamPolicy<Kokkos::DefaultExecutionSpace::scratch_memory_space>::member_type member_type;

public:
	Variables(CartesianMesh2D& aMesh);
	~Variables();

	void jsonInit(const char* jsonContent);

	void simulate();
	KOKKOS_INLINE_FUNCTION
	void init_arrayOption() noexcept;
	KOKKOS_INLINE_FUNCTION
	void init_optionDim() noexcept;
	KOKKOS_INLINE_FUNCTION
	void newVar(const member_type& teamMember) noexcept;
	KOKKOS_INLINE_FUNCTION
	void setUnknownDim() noexcept;
	KOKKOS_INLINE_FUNCTION
	void init_dynamicArray() noexcept;
	KOKKOS_INLINE_FUNCTION
	void init_dynamicOptArray() noexcept;
	KOKKOS_INLINE_FUNCTION
	void init_optionArray() noexcept;

private:
	/**
	 * Utility function to get work load for each team of threads
	 * In  : thread and number of element to use for computation
	 * Out : pair of indexes, 1st one for start of chunk, 2nd one for size of chunk
	 */
	const std::pair<size_t, size_t> computeTeamWorkRange(const member_type& thread, const size_t& nb_elmt) noexcept;

	// Json block of options
	rapidjson::Document jsonDocument;

	// Mesh and mesh variables
	CartesianMesh2D& mesh;
	size_t nbNodes, maxCellsOfNode;

	// Options and global variables
	static constexpr double maxTime = 0.1;
	static constexpr int maxIter = 500;
	static constexpr double deltat = 1.0;
	double t;
	RealArray1D<2> arrayOption;
	static constexpr int dim = 2;
	RealArray1D<2> v1;
	RealArray1D<dim> v2;
	Kokkos::View<RealArray1D<dim>*> X;
	int unknownDim;
	RealArray1D<0> dynamicArray;
	int optionDim;
	RealArray1D<0> dynamicOptArray;
	RealArray1D<0> optionArray;

	// Timers
	Timer globalTimer;
	Timer cpuTimer;
	Timer ioTimer;
};

#endif
