/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __IREMAP_H_
#define __IREMAP_H_

using namespace Arcane;

class IRemap
{
public:
	IRemap() {}
	virtual ~IRemap() {}

public:
	virtual void rj1() = 0;
	virtual void rj2() = 0;
};

#endif
