# DO NOT EDIT THIS FILE - it is machine generated
#
#!/bin/sh
#
#
# Excute heatequation.py with the installed python3.
# Numpy and plyvel modules must be installed.
# To reproduce results, use runvenv.sh.
#
export N_WS_PATH=$HOME/WorkspaceDev/NabLab/plugins/fr.cea.nabla.ui/examples
export PYTHONPATH=$N_WS_PATH/.nablab/mesh/cartesianmesh2dnumpy:$N_WS_PATH/.nablab/linearalgebra/linearalgebranumpy
python3 heatequation.py $*
