# DO NOT EDIT THIS FILE - it is machine generated
#
#!/bin/sh
#
export PYTHONPATH=/home/lelandaisb/workspaces/NabLab/plugins/fr.cea.nabla.ui/examples/.nablab/mesh/cartesianmesh2dnumpy:/home/lelandaisb/workspaces/NabLab/plugins/fr.cea.nabla.ui/examples/.nablab/linearalgebra/linearalgebranumpy
python3 glace2d.py $*
