/* DO NOT EDIT THIS FILE - it is machine generated */

package affectations;

import java.io.FileReader;
import java.io.IOException;
import java.util.stream.IntStream;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import com.google.gson.JsonElement;

import fr.cea.nabla.javalib.*;
import fr.cea.nabla.javalib.mesh.*;

public final class Affectations
{
	// Json block of options
	private JsonObject options;

	// Mesh and mesh variables
	private final CartesianMesh2D mesh;
	@SuppressWarnings("unused")
	private final int nbNodes, nbCells;

	// Options and global variables
	int n;
	int k;
	static final double maxTime = 0.1;
	static final int maxIter = 500;
	static final double deltat = 1.0;
	double t_n;
	double t_nplus1;
	double t_n0;
	double[] u_n;
	double[] u_nplus1;
	double[] u_n0;
	double[][] X;
	double[][] e1;
	double[][] e2_n;
	double[][] e2_nplus1;
	double[][] e2_nplus1_k;
	double[][] e2_nplus1_kplus1;
	double[][] e2_nplus1_k0;
	double[][] e_n;
	double[][] e_nplus1;
	double[][] e_n0;

	public Affectations(CartesianMesh2D aMesh)
	{
		// Mesh and mesh variables initialization
		mesh = aMesh;
		nbNodes = mesh.getNbNodes();
		nbCells = mesh.getNbCells();

		// Allocate arrays
		u_n = new double[2];
		u_nplus1 = new double[2];
		u_n0 = new double[2];
		X = new double[nbNodes][2];
		e1 = new double[nbCells][2];
		e2_n = new double[nbCells][2];
		e2_nplus1 = new double[nbCells][2];
		e2_nplus1_k = new double[nbCells][2];
		e2_nplus1_kplus1 = new double[nbCells][2];
		e2_nplus1_k0 = new double[nbCells][2];
		e_n = new double[nbCells][2];
		e_nplus1 = new double[nbCells][2];
		e_n0 = new double[nbCells][2];

		// Copy node coordinates
		double[][] gNodes = mesh.getGeometry().getNodes();
		IntStream.range(0, nbNodes).parallel().forEach(rNodes ->
		{
			X[rNodes][0] = gNodes[rNodes][0];
			X[rNodes][1] = gNodes[rNodes][1];
		});
	}

	public void jsonInit(final String jsonContent)
	{
		final Gson gson = new Gson();
		options = gson.fromJson(jsonContent, JsonObject.class);
	}

	/**
	 * Job computeE1 called @1.0 in executeTimeLoopN method.
	 * In variables: e_n
	 * Out variables: e1
	 */
	protected void computeE1()
	{
		IntStream.range(0, nbCells).parallel().forEach(cCells -> 
		{
			e1[cCells] = ArrayOperations.plus(e_n[cCells], 3.0);
		});
	}

	/**
	 * Job computeE2 called @1.0 in executeTimeLoopK method.
	 * In variables: e2_nplus1_k
	 * Out variables: e2_nplus1_kplus1
	 */
	protected void computeE2()
	{
		IntStream.range(0, nbCells).parallel().forEach(cCells -> 
		{
			e2_nplus1_kplus1[cCells] = ArrayOperations.plus(e2_nplus1_k[cCells], 0.4);
		});
	}

	/**
	 * Job initE called @1.0 in simulate method.
	 * In variables: 
	 * Out variables: e_n0
	 */
	protected void initE()
	{
		IntStream.range(0, nbCells).parallel().forEach(cCells -> 
		{
			e_n0[cCells] = new double[] {0.0, 0.0};
		});
	}

	/**
	 * Job initTandU called @1.0 in simulate method.
	 * In variables: 
	 * Out variables: t_n0, u_n0
	 */
	protected void initTandU()
	{
		t_n0 = 0.0;
		u_n0 = new double[] {0.0, 0.0};
	}

	/**
	 * Job updateT called @1.0 in executeTimeLoopN method.
	 * In variables: deltat, t_n
	 * Out variables: t_nplus1
	 */
	protected void updateT()
	{
		t_nplus1 = t_n + deltat;
	}

	/**
	 * Job updateU called @1.0 in executeTimeLoopN method.
	 * In variables: u_n
	 * Out variables: u_nplus1
	 */
	protected void updateU()
	{
		u_nplus1 = ArrayOperations.multiply(u_n, 2);
	}

	/**
	 * Job initE2 called @2.0 in executeTimeLoopN method.
	 * In variables: e1
	 * Out variables: e2_nplus1_k0
	 */
	protected void initE2()
	{
		IntStream.range(0, nbCells).parallel().forEach(cCells -> 
		{
			for (int i1=0; i1<2; i1++)
			{
				e2_nplus1_k0[cCells][i1] = e1[cCells][i1];
			}
		});
	}

	/**
	 * Job setUpTimeLoopN called @2.0 in simulate method.
	 * In variables: e_n0, t_n0, u_n0
	 * Out variables: e_n, t_n, u_n
	 */
	protected void setUpTimeLoopN()
	{
		t_n = t_n0;
		for (int i1=0; i1<2; i1++)
		{
			u_n[i1] = u_n0[i1];
		}
		IntStream.range(0, nbCells).parallel().forEach(i1Cells -> 
		{
			for (int i1=0; i1<2; i1++)
			{
				e_n[i1Cells][i1] = e_n0[i1Cells][i1];
			}
		});
	}

	/**
	 * Job executeTimeLoopN called @3.0 in simulate method.
	 * In variables: e2_n, e_n, maxIter, maxTime, n, t_n, t_nplus1, u_n
	 * Out variables: e2_nplus1, e_nplus1, t_nplus1, u_nplus1
	 */
	protected void executeTimeLoopN()
	{
		n = 0;
		boolean continueLoop = true;
		do
		{
			n++;
			System.out.printf("START ITERATION n: %5d - t: %5.5f - deltat: %5.5f\n", n, t_n, deltat);
		
			computeE1(); // @1.0
			updateT(); // @1.0
			updateU(); // @1.0
			initE2(); // @2.0
			setUpTimeLoopK(); // @3.0
			executeTimeLoopK(); // @4.0
			tearDownTimeLoopK(); // @5.0
			updateE(); // @6.0
		
			// Evaluate loop condition with variables at time n
			continueLoop = (n + 1 < maxIter && t_nplus1 < maxTime);
		
			t_n = t_nplus1;
			for (int i1=0; i1<2; i1++)
			{
				u_n[i1] = u_nplus1[i1];
			}
			IntStream.range(0, nbCells).parallel().forEach(i1Cells -> 
			{
				for (int i1=0; i1<2; i1++)
				{
					e2_n[i1Cells][i1] = e2_nplus1[i1Cells][i1];
				}
			});
			IntStream.range(0, nbCells).parallel().forEach(i1Cells -> 
			{
				for (int i1=0; i1<2; i1++)
				{
					e_n[i1Cells][i1] = e_nplus1[i1Cells][i1];
				}
			});
		} while (continueLoop);
		
		System.out.printf("FINAL TIME: %5.5f - deltat: %5.5f\n", t_n, deltat);
	}

	/**
	 * Job setUpTimeLoopK called @3.0 in executeTimeLoopN method.
	 * In variables: e2_nplus1_k0
	 * Out variables: e2_nplus1_k
	 */
	protected void setUpTimeLoopK()
	{
		IntStream.range(0, nbCells).parallel().forEach(i1Cells -> 
		{
			for (int i1=0; i1<2; i1++)
			{
				e2_nplus1_k[i1Cells][i1] = e2_nplus1_k0[i1Cells][i1];
			}
		});
	}

	/**
	 * Job executeTimeLoopK called @4.0 in executeTimeLoopN method.
	 * In variables: e2_nplus1_k, k
	 * Out variables: e2_nplus1_kplus1
	 */
	protected void executeTimeLoopK()
	{
		k = 0;
		boolean continueLoop = true;
		do
		{
			k++;
			System.out.printf("Start iteration k: %5d\n", k);
		
			computeE2(); // @1.0
		
			// Evaluate loop condition with variables at time n
			continueLoop = (k + 1 < 10);
		
			IntStream.range(0, nbCells).parallel().forEach(i1Cells -> 
			{
				for (int i1=0; i1<2; i1++)
				{
					e2_nplus1_k[i1Cells][i1] = e2_nplus1_kplus1[i1Cells][i1];
				}
			});
		} while (continueLoop);
	}

	/**
	 * Job tearDownTimeLoopK called @5.0 in executeTimeLoopN method.
	 * In variables: e2_nplus1_kplus1
	 * Out variables: e2_nplus1
	 */
	protected void tearDownTimeLoopK()
	{
		IntStream.range(0, nbCells).parallel().forEach(i1Cells -> 
		{
			for (int i1=0; i1<2; i1++)
			{
				e2_nplus1[i1Cells][i1] = e2_nplus1_kplus1[i1Cells][i1];
			}
		});
	}

	/**
	 * Job updateE called @6.0 in executeTimeLoopN method.
	 * In variables: e2_nplus1
	 * Out variables: e_nplus1
	 */
	protected void updateE()
	{
		IntStream.range(0, nbCells).parallel().forEach(cCells -> 
		{
			e_nplus1[cCells] = ArrayOperations.minus(e2_nplus1[cCells], 3);
		});
	}

	public void simulate()
	{
		System.out.println("Start execution of affectations");
		initE(); // @1.0
		initTandU(); // @1.0
		setUpTimeLoopN(); // @2.0
		executeTimeLoopN(); // @3.0
		System.out.println("End of execution of affectations");
	}

	public static void main(String[] args) throws IOException
	{
		if (args.length == 1)
		{
			final String dataFileName = args[0];
			final Gson gson = new Gson();
			final JsonObject o = gson.fromJson(new FileReader(dataFileName), JsonObject.class);

			// Mesh instanciation
			assert(o.has("mesh"));
			CartesianMesh2D mesh = new CartesianMesh2D();
			mesh.jsonInit(o.get("mesh").toString());

			// Module instanciation(s)
			Affectations affectations = new Affectations(mesh);
			if (o.has("affectations")) affectations.jsonInit(o.get("affectations").toString());

			// Start simulation
			affectations.simulate();
		}
		else
		{
			System.err.println("[ERROR] Wrong number of arguments: expected 1, actual " + args.length);
			System.err.println("        Expecting user data file name, for example Affectations.json");
			System.exit(1);
		}
	}
};
