/* DO NOT EDIT THIS FILE - it is machine generated */

#include "Iteration.h"
#include <rapidjson/document.h>
#include <rapidjson/istreamwrapper.h>
#include <rapidjson/stringbuffer.h>
#include <rapidjson/writer.h>


/******************** Free functions definitions ********************/

namespace iterationfreefuncs
{
bool assertEquals(double expected, double actual)
{
	const bool ret((expected == actual));
	if (!ret) 
	{
		throw std::runtime_error("** Assertion failed");
	}
	return ret;
}
}

/******************** Module definition ********************/

Iteration::Iteration(CartesianMesh2D& aMesh)
: mesh(aMesh)
, nbNodes(mesh.getNbNodes())
, nbCells(mesh.getNbCells())
, X(nbNodes)
, vn_n(nbCells)
, vn_nplus1(nbCells)
, vn_n0(nbCells)
, vk_n(nbCells)
, vk_nplus1(nbCells)
, vk_nplus1_k(nbCells)
, vk_nplus1_kplus1(nbCells)
, vk_nplus1_k0(nbCells)
, vl_n(nbCells)
, vl_nplus1(nbCells)
, vl_nplus1_l(nbCells)
, vl_nplus1_lplus1(nbCells)
, vl_nplus1_l0(nbCells)
{
}

Iteration::~Iteration()
{
}

void
Iteration::jsonInit(const char* jsonContent)
{
	rapidjson::Document document;
	assert(!document.Parse(jsonContent).HasParseError());
	assert(document.IsObject());
	const rapidjson::Value::Object& options = document.GetObject();

	n = 0;
	k = 0;
	l = 0;

	// Copy node coordinates
	const auto& gNodes = mesh.getGeometry()->getNodes();
	for (size_t rNodes=0; rNodes<nbNodes; rNodes++)
	{
		X[rNodes][0] = gNodes[rNodes][0];
		X[rNodes][1] = gNodes[rNodes][1];
	}
}

/**
 * Job computeTn called @1.0 in executeTimeLoopN method.
 * In variables: delta_t, t_n
 * Out variables: t_nplus1
 */
void Iteration::computeTn() noexcept
{
	t_nplus1 = t_n + delta_t;
}

/**
 * Job iniTime called @1.0 in simulate method.
 * In variables: 
 * Out variables: t_n0
 */
void Iteration::iniTime() noexcept
{
	t_n0 = 0.0;
}

/**
 * Job iniVk called @1.0 in simulate method.
 * In variables: 
 * Out variables: vk_nplus1_k0
 */
void Iteration::iniVk() noexcept
{
	#pragma omp parallel for
	for (size_t jCells=0; jCells<nbCells; jCells++)
	{
		vk_nplus1_k0[jCells] = 0.0;
	}
}

/**
 * Job iniVn called @1.0 in simulate method.
 * In variables: 
 * Out variables: vn_n0
 */
void Iteration::iniVn() noexcept
{
	#pragma omp parallel for
	for (size_t jCells=0; jCells<nbCells; jCells++)
	{
		vn_n0[jCells] = 0.0;
	}
}

/**
 * Job setUpTimeLoopK called @1.0 in executeTimeLoopN method.
 * In variables: vk_nplus1_k0
 * Out variables: vk_nplus1_k
 */
void Iteration::setUpTimeLoopK() noexcept
{
	#pragma omp parallel for
	for (size_t i1Cells=0; i1Cells<nbCells; i1Cells++)
	{
		vk_nplus1_k[i1Cells] = vk_nplus1_k0[i1Cells];
	}
}

/**
 * Job updateVk called @1.0 in executeTimeLoopK method.
 * In variables: vk_nplus1_k
 * Out variables: vk_nplus1_kplus1
 */
void Iteration::updateVk() noexcept
{
	#pragma omp parallel for
	for (size_t jCells=0; jCells<nbCells; jCells++)
	{
		vk_nplus1_kplus1[jCells] = vk_nplus1_k[jCells] + 2;
	}
}

/**
 * Job updateVl called @1.0 in executeTimeLoopL method.
 * In variables: vl_nplus1_l
 * Out variables: vl_nplus1_lplus1
 */
void Iteration::updateVl() noexcept
{
	#pragma omp parallel for
	for (size_t jCells=0; jCells<nbCells; jCells++)
	{
		vl_nplus1_lplus1[jCells] = vl_nplus1_l[jCells] + 1;
	}
}

/**
 * Job executeTimeLoopK called @2.0 in executeTimeLoopN method.
 * In variables: k, maxIterK, vk_nplus1_k
 * Out variables: vk_nplus1_kplus1
 */
void Iteration::executeTimeLoopK() noexcept
{
	k = 0;
	bool continueLoop = true;
	do
	{
		k++;
		updateVk(); // @1.0
		
	
		// Evaluate loop condition with variables at time n
		continueLoop = (k < maxIterK);
	
		#pragma omp parallel for
		for (size_t i1Cells=0; i1Cells<nbCells; i1Cells++)
		{
			vk_nplus1_k[i1Cells] = vk_nplus1_kplus1[i1Cells];
		}
	} while (continueLoop);
}

/**
 * Job setUpTimeLoopN called @2.0 in simulate method.
 * In variables: t_n0, vn_n0
 * Out variables: t_n, vn_n
 */
void Iteration::setUpTimeLoopN() noexcept
{
	t_n = t_n0;
	#pragma omp parallel for
	for (size_t i1Cells=0; i1Cells<nbCells; i1Cells++)
	{
		vn_n[i1Cells] = vn_n0[i1Cells];
	}
}

/**
 * Job executeTimeLoopN called @3.0 in simulate method.
 * In variables: maxIterN, n, t_n, vk_n, vl_n, vn_n
 * Out variables: t_nplus1, vk_nplus1, vl_nplus1, vn_nplus1
 */
void Iteration::executeTimeLoopN() noexcept
{
	n = 0;
	bool continueLoop = true;
	do
	{
		globalTimer.start();
		cpuTimer.start();
		n++;
		if (n!=1)
			std::cout << "[" << __CYAN__ << __BOLD__ << setw(3) << n << __RESET__ "] t = " << __BOLD__
				<< setiosflags(std::ios::scientific) << setprecision(8) << setw(16) << t_n << __RESET__;
	
		computeTn(); // @1.0
		setUpTimeLoopK(); // @1.0
		executeTimeLoopK(); // @2.0
		tearDownTimeLoopK(); // @3.0
		iniVl(); // @4.0
		oracleVk(); // @4.0
		setUpTimeLoopL(); // @5.0
		executeTimeLoopL(); // @6.0
		tearDownTimeLoopL(); // @7.0
		oracleVl(); // @8.0
		updateVn(); // @8.0
		oracleVn(); // @9.0
		
	
		// Evaluate loop condition with variables at time n
		continueLoop = (n < maxIterN);
	
		t_n = t_nplus1;
		#pragma omp parallel for
		for (size_t i1Cells=0; i1Cells<nbCells; i1Cells++)
		{
			vn_n[i1Cells] = vn_nplus1[i1Cells];
		}
		#pragma omp parallel for
		for (size_t i1Cells=0; i1Cells<nbCells; i1Cells++)
		{
			vk_n[i1Cells] = vk_nplus1[i1Cells];
		}
		#pragma omp parallel for
		for (size_t i1Cells=0; i1Cells<nbCells; i1Cells++)
		{
			vl_n[i1Cells] = vl_nplus1[i1Cells];
		}
	
		cpuTimer.stop();
		globalTimer.stop();
	
		// Timers display
			std::cout << " {CPU: " << __BLUE__ << cpuTimer.print(true) << __RESET__ ", IO: " << __RED__ << "none" << __RESET__ << "} ";
		
		// Progress
		std::cout << progress_bar(n, maxIterN, t_n, maxTime, 25);
		std::cout << __BOLD__ << __CYAN__ << Timer::print(
			eta(n, maxIterN, t_n, maxTime, delta_t, globalTimer), true)
			<< __RESET__ << "\r";
		std::cout.flush();
	
		cpuTimer.reset();
		ioTimer.reset();
	} while (continueLoop);
}

/**
 * Job tearDownTimeLoopK called @3.0 in executeTimeLoopN method.
 * In variables: vk_nplus1_kplus1
 * Out variables: vk_nplus1
 */
void Iteration::tearDownTimeLoopK() noexcept
{
	#pragma omp parallel for
	for (size_t i1Cells=0; i1Cells<nbCells; i1Cells++)
	{
		vk_nplus1[i1Cells] = vk_nplus1_kplus1[i1Cells];
	}
}

/**
 * Job iniVl called @4.0 in executeTimeLoopN method.
 * In variables: vk_nplus1
 * Out variables: vl_nplus1_l0
 */
void Iteration::iniVl() noexcept
{
	#pragma omp parallel for
	for (size_t jCells=0; jCells<nbCells; jCells++)
	{
		vl_nplus1_l0[jCells] = vk_nplus1[jCells] + 8;
	}
}

/**
 * Job oracleVk called @4.0 in executeTimeLoopN method.
 * In variables: vk_nplus1
 * Out variables: 
 */
void Iteration::oracleVk() noexcept
{
	#pragma omp parallel for
	for (size_t jCells=0; jCells<nbCells; jCells++)
	{
		const bool testVk(iterationfreefuncs::assertEquals(12.0, vk_nplus1[jCells]));
	}
}

/**
 * Job setUpTimeLoopL called @5.0 in executeTimeLoopN method.
 * In variables: vl_nplus1_l0
 * Out variables: vl_nplus1_l
 */
void Iteration::setUpTimeLoopL() noexcept
{
	#pragma omp parallel for
	for (size_t i1Cells=0; i1Cells<nbCells; i1Cells++)
	{
		vl_nplus1_l[i1Cells] = vl_nplus1_l0[i1Cells];
	}
}

/**
 * Job executeTimeLoopL called @6.0 in executeTimeLoopN method.
 * In variables: l, maxIterL, vl_nplus1_l
 * Out variables: vl_nplus1_lplus1
 */
void Iteration::executeTimeLoopL() noexcept
{
	l = 0;
	bool continueLoop = true;
	do
	{
		l++;
		updateVl(); // @1.0
		
	
		// Evaluate loop condition with variables at time n
		continueLoop = (l < maxIterL);
	
		#pragma omp parallel for
		for (size_t i1Cells=0; i1Cells<nbCells; i1Cells++)
		{
			vl_nplus1_l[i1Cells] = vl_nplus1_lplus1[i1Cells];
		}
	} while (continueLoop);
}

/**
 * Job tearDownTimeLoopL called @7.0 in executeTimeLoopN method.
 * In variables: vl_nplus1_lplus1
 * Out variables: vl_nplus1
 */
void Iteration::tearDownTimeLoopL() noexcept
{
	#pragma omp parallel for
	for (size_t i1Cells=0; i1Cells<nbCells; i1Cells++)
	{
		vl_nplus1[i1Cells] = vl_nplus1_lplus1[i1Cells];
	}
}

/**
 * Job oracleVl called @8.0 in executeTimeLoopN method.
 * In variables: vl_nplus1
 * Out variables: 
 */
void Iteration::oracleVl() noexcept
{
	#pragma omp parallel for
	for (size_t jCells=0; jCells<nbCells; jCells++)
	{
		const bool testVl(iterationfreefuncs::assertEquals(27.0, vl_nplus1[jCells]));
	}
}

/**
 * Job updateVn called @8.0 in executeTimeLoopN method.
 * In variables: vl_nplus1, vn_n
 * Out variables: vn_nplus1
 */
void Iteration::updateVn() noexcept
{
	#pragma omp parallel for
	for (size_t jCells=0; jCells<nbCells; jCells++)
	{
		vn_nplus1[jCells] = vn_n[jCells] + vl_nplus1[jCells] * 2;
	}
}

/**
 * Job oracleVn called @9.0 in executeTimeLoopN method.
 * In variables: n, vn_nplus1
 * Out variables: 
 */
void Iteration::oracleVn() noexcept
{
	#pragma omp parallel for
	for (size_t jCells=0; jCells<nbCells; jCells++)
	{
		const bool testVn(iterationfreefuncs::assertEquals(54.0 * n, vn_nplus1[jCells]));
	}
}

void Iteration::simulate()
{
	std::cout << "\n" << __BLUE_BKG__ << __YELLOW__ << __BOLD__ <<"\tStarting Iteration ..." << __RESET__ << "\n\n";
	
	std::cout << "[" << __GREEN__ << "TOPOLOGY" << __RESET__ << "]  HWLOC unavailable cannot get topological informations" << std::endl;
	
	std::cout << "[" << __GREEN__ << "OUTPUT" << __RESET__ << "]    " << __BOLD__ << "Disabled" << __RESET__ << std::endl;

	iniTime(); // @1.0
	iniVk(); // @1.0
	iniVn(); // @1.0
	setUpTimeLoopN(); // @2.0
	executeTimeLoopN(); // @3.0
	
	std::cout << "\nFinal time = " << t_n << endl;
	std::cout << __YELLOW__ << "\n\tDone ! Took " << __MAGENTA__ << __BOLD__ << globalTimer.print() << __RESET__ << std::endl;
}

int main(int argc, char* argv[]) 
{
	string dataFile;
	int ret = 0;
	
	if (argc == 2)
	{
		dataFile = argv[1];
	}
	else
	{
		std::cerr << "[ERROR] Wrong number of arguments. Expecting 1 arg: dataFile." << std::endl;
		std::cerr << "(Iteration.json)" << std::endl;
		return -1;
	}
	
	// read json dataFile
	ifstream ifs(dataFile);
	rapidjson::IStreamWrapper isw(ifs);
	rapidjson::Document d;
	d.ParseStream(isw);
	assert(d.IsObject());
	
	// Mesh instanciation
	CartesianMesh2D mesh;
	assert(d.HasMember("mesh"));
	rapidjson::StringBuffer strbuf;
	rapidjson::Writer<rapidjson::StringBuffer> writer(strbuf);
	d["mesh"].Accept(writer);
	mesh.jsonInit(strbuf.GetString());
	
	// Module instanciation(s)
	Iteration* iteration = new Iteration(mesh);
	assert(d.HasMember("iteration"));
	{
		rapidjson::StringBuffer strbuf;
		rapidjson::Writer<rapidjson::StringBuffer> writer(strbuf);
		d["iteration"].Accept(writer);
		iteration->jsonInit(strbuf.GetString());
	}
	
	// Start simulation
	// Simulator must be a pointer when a finalize is needed at the end (Kokkos, omp...)
	iteration->simulate();
	
	delete iteration;
	return ret;
}
