/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __GLACE2DMODULE_H_
#define __GLACE2DMODULE_H_

#include <arcane/utils/Array.h>
#include <arcane/datatype/RealArrayVariant.h>
#include <arcane/datatype/RealArray2Variant.h>
#include "Glace2d_axl.h"
#include "CartesianMesh2D.h"

using namespace Arcane;

/*** Free functions **********************************************************/

namespace glace2dfreefuncs
{
	const Real det(RealArray2Variant a);
	RealArrayVariant perp(RealArrayVariant a);
	const Real dot(RealArrayVariant a, RealArrayVariant b);
	const Real norm(RealArrayVariant a);
	RealArray2Variant tensProduct(RealArrayVariant a, RealArrayVariant b);
	RealArrayVariant matVectProduct(RealArray2Variant a, RealArrayVariant b);
	const Real trace(RealArray2Variant a);
	RealArray2Variant inverse(RealArray2Variant a);
	RealArrayVariant sumR1(RealArrayVariant a, RealArrayVariant b);
	const Real sumR0(const Real a, const Real b);
	RealArray2Variant sumR2(RealArray2Variant a, RealArray2Variant b);
	const Real minR0(const Real a, const Real b);
	RealArrayVariant operatorAdd(RealArrayVariant a, RealArrayVariant b);
	RealArray2Variant operatorAdd(RealArray2Variant a, RealArray2Variant b);
	RealArrayVariant operatorMult(const Real a, RealArrayVariant b);
	RealArrayVariant operatorSub(RealArrayVariant a, RealArrayVariant b);
	RealArray2Variant operatorMult(const Real a, RealArray2Variant b);
	RealArray2Variant operatorSub(RealArray2Variant a, RealArray2Variant b);
	RealArray2Variant operatorMult(RealArray2Variant a, RealArray2Variant b);
	RealArray2Variant operatorMult(RealArray2Variant a, const Real b);
}

/*** Module ******************************************************************/

class Glace2dModule
: public ArcaneGlace2dObject
{
public:
	Glace2dModule(const ModuleBuildInfo& mbi);
	~Glace2dModule() {}

	virtual void init() override;
	virtual void executeTimeLoopN() override;

	VersionInfo versionInfo() const override { return VersionInfo(1, 0, 0); }

private:
	void computeCjr();
	void computeInternalEnergy();
	void iniCjrIc();
	void iniTime();
	void computeLjr();
	void computeV();
	void initialize();
	void setUpTimeLoopN();
	void computeDensity();
	void computeEOSp();
	void computeEOSc();
	void computeAjr();
	void computedeltatj();
	void computeAr();
	void computeBr();
	void computeDt();
	void computeBoundaryConditions();
	void computeBt();
	void computeMt();
	void computeTn();
	void computeU();
	void computeFjr();
	void computeXn();
	void computeEn();
	void computeUn();

private:
	// mesh attributes
	CartesianMesh2D* m_mesh;

	// other attributes
	Int32 m_lastDump;
	Int32 m_n;
	static constexpr Real m_gamma = 1.4;
	static constexpr Real m_xInterface = 0.5;
	static constexpr Real m_deltatCfl = 0.4;
	static constexpr Real m_rhoIniZg = 1.0;
	static constexpr Real m_rhoIniZd = 0.125;
	static constexpr Real m_pIniZg = 1.0;
	static constexpr Real m_pIniZd = 0.1;
	Real m_t_n;
	Real m_t_nplus1;
	Real m_t_n0;
	Real m_deltat;
};

#endif
