/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class batilib_BatiLibCppJni */

#ifndef _Included_batilib_BatiLibCppJni
#define _Included_batilib_BatiLibCppJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     batilib_BatiLibCppJni
 * Method:    nativeNew
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_batilib_BatiLibCppJni_nativeNew
  (JNIEnv *, jobject);

/*
 * Class:     batilib_BatiLibCppJni
 * Method:    jsonInit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_batilib_BatiLibCppJni_jsonInit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     batilib_BatiLibCppJni
 * Method:    nextWaveHeight
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_batilib_BatiLibCppJni_nextWaveHeight
  (JNIEnv *, jobject);

/*
 * Class:     batilib_BatiLibCppJni
 * Method:    nextDepth1
 * Signature: (D[D)D
 */
JNIEXPORT jdouble JNICALL Java_batilib_BatiLibCppJni_nextDepth1
  (JNIEnv *, jobject, jdouble, jdoubleArray);

/*
 * Class:     batilib_BatiLibCppJni
 * Method:    nextDepth2
 * Signature: (D[[D)D
 */
JNIEXPORT jdouble JNICALL Java_batilib_BatiLibCppJni_nextDepth2
  (JNIEnv *, jobject, jdouble, jobjectArray);

/*
 * Class:     batilib_BatiLibCppJni
 * Method:    nextDepth3
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_batilib_BatiLibCppJni_nextDepth3
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     batilib_BatiLibCppJni
 * Method:    nextDepth4
 * Signature: ([[D)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_batilib_BatiLibCppJni_nextDepth4
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
