"""
DO NOT EDIT THIS FILE - it is machine generated
"""
import sys
import json
import numpy as np
from cartesianmesh2d import CartesianMesh2D

class R1:

	def __init__(self, mesh):
		self.__mesh = mesh
		self.__nbCells = mesh.nbCells

	def jsonInit(self, jsonContent):
		self.rv3 = np.empty((self.__nbCells), dtype=np.double)

	"""
	 Job rj1 called @2.0 in simulate method.
	 In variables: hv1
	 Out variables: hv4
	"""
	def _rj1(self):
		for cCells in range(self.__nbCells):
			self._mainModule.hv4[cCells] = self._mainModule.hv1[cCells] * 2.0

	"""
	 Job rj2 called @3.0 in simulate method.
	 In variables: hv4
	 Out variables: rv3
	"""
	def _rj2(self):
		for cCells in range(self.__nbCells):
			self.rv3[cCells] = self._mainModule.hv4[cCells] * 3.0

	def set_mainModule(self, value):
		self._mainModule = value
		self._mainModule.set_r1(self)
